# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy to NuGet

on:
  push:
    branches: [ "main", "alpha" ]
  pull_request:
    branches: [ "main", "alpha" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:
    - uses: actions/checkout@v3
    
    - name: Set variables
      id: setvars
      run: |
        if [[ "${{github.base_ref}}" == "master" || "${{github.ref}}" == "refs/heads/master" ]]; then
          echo "VERSION_SUFFIX=" >> "$GITHUB_ENV"
        fi

        if [[ "${{github.base_ref}}" == "alpha" || "${{github.ref}}" == "refs/heads/alpha" ]]; then
        echo "VERSION_SUFFIX=alpha.${{github.run_number}}" >> "$GITHUB_ENV"
        fi

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        cache: true
        cache-dependency-path: '**/packages.lock.json'
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
    
    - name: Build solution and generate NuGet package
      run: dotnet pack -c Release -o out --version-suffix "$VERSION_SUFFIX" src/Root16.Sprout
      
    - name: Push
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push out/*.nupkg --skip-duplicate --no-symbols --api-key $NUGET_API_KEY
